//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIA_DLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CIEntities1 : DbContext
    {
        public CIEntities1()
            : base("name=CIEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CIUserMaster> CIUserMasters { get; set; }
        public virtual DbSet<CIBranchMst> CIBranchMsts { get; set; }
        public virtual DbSet<CIClientEntry> CIClientEntries { get; set; }
        public virtual DbSet<CIInvoiceDetail> CIInvoiceDetails { get; set; }
        public virtual DbSet<CIInvoiceEntry> CIInvoiceEntries { get; set; }
    
        public virtual ObjectResult<ci_reportview__Result> ci_reportview_(Nullable<int> report_typ, string clientName, string report_options, Nullable<System.DateTime> fromdate, Nullable<System.DateTime> enddate)
        {
            var report_typParameter = report_typ.HasValue ?
                new ObjectParameter("report_typ", report_typ) :
                new ObjectParameter("report_typ", typeof(int));
    
            var clientNameParameter = clientName != null ?
                new ObjectParameter("clientName", clientName) :
                new ObjectParameter("clientName", typeof(string));
    
            var report_optionsParameter = report_options != null ?
                new ObjectParameter("report_options", report_options) :
                new ObjectParameter("report_options", typeof(string));
    
            var fromdateParameter = fromdate.HasValue ?
                new ObjectParameter("fromdate", fromdate) :
                new ObjectParameter("fromdate", typeof(System.DateTime));
    
            var enddateParameter = enddate.HasValue ?
                new ObjectParameter("enddate", enddate) :
                new ObjectParameter("enddate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ci_reportview__Result>("ci_reportview_", report_typParameter, clientNameParameter, report_optionsParameter, fromdateParameter, enddateParameter);
        }
    }
}
