//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIA_DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIBranchMst
    {
        public int CIBranchMst_Tbl_PK { get; set; }
        public string CBM_BranchCode { get; set; }
        public string CBM_BranchName { get; set; }
        public string CBM_Address { get; set; }
        public string CBM_RegNo { get; set; }
        public string CBM_TVANo { get; set; }
        public string CBM_Email { get; set; }
        public Nullable<int> CBM_Tel { get; set; }
        public string CBM_Web { get; set; }
        public string CBM_GeneralTerms { get; set; }
        public string CBM_FooterText { get; set; }
        public decimal CBM_TVAPer { get; set; }
        public string CBM_ActiveStatus { get; set; }
        public int CBM_CreateBy { get; set; }
        public System.DateTime CBM_CreateOn { get; set; }
        public Nullable<int> CBM_UpdateBy { get; set; }
        public Nullable<System.DateTime> CBM_UpdateOn { get; set; }
    }
}
