//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIA_DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIClientEntry
    {
        public int CICE__ID { get; set; }
        public string CIclientnon_ID { get; set; }
        public string CICE_nomclient { get; set; }
        public string CICE_c_adresse { get; set; }
        public string CICE_c_codepostale { get; set; }
        public string CICE_c_ville { get; set; }
        public string CICE_c_pays { get; set; }
        public string CICE_c_courriel { get; set; }
        public string CICE_c_lignefixe_non { get; set; }
        public string CICE_c_mobile_non { get; set; }
        public string CICE_nom_organisme { get; set; }
        public string CICE_numero_enregistr_professional { get; set; }
        public string CICE_facture_adresse { get; set; }
        public string CICE_o_codepostale { get; set; }
        public string CICE_o_ville { get; set; }
        public string CICE_o_pays { get; set; }
        public string CICE_o_courriel { get; set; }
        public string CICE_o_lignefixe_non { get; set; }
        public string CICE_o_mobile_non { get; set; }
        public string CICE_payment_terms { get; set; }
        public string CICE_comments { get; set; }
        public string CICE_ActiveStatus { get; set; }
        public string CICE_CreateBy { get; set; }
        public System.DateTime CICE_CreateOn { get; set; }
        public string CICE_UpdateBy { get; set; }
        public Nullable<System.DateTime> CICE_UpdateOn { get; set; }
    }
}
