//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIA_DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIInvoiceDetail
    {
        public int CIID_ID { get; set; }
        public string CIIE_invoice_no_ID { get; set; }
        public string CIID_refernce { get; set; }
        public string CIID_n_declaration { get; set; }
        public string CIID_intervention_taxable { get; set; }
        public string CIID_intervention_nontaxable { get; set; }
        public string CIID_at_tva_douane { get; set; }
        public Nullable<int> CIID_tva_perctage { get; set; }
        public string CIID_UpdateBy { get; set; }
        public Nullable<System.DateTime> CIID_UpdateOn { get; set; }
    }
}
