//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIA_DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIInvoiceEntry
    {
        public int CIIE__ID { get; set; }
        public string CIIE_invoice_no_ID { get; set; }
        public string CIIE_entrd_invoice_no { get; set; }
        public System.DateTime CIIE_invoice_currdate { get; set; }
        public Nullable<System.DateTime> CIIE_invoice_seldate { get; set; }
        public string CIIE_client_sel { get; set; }
        public string CIIE_invoice_genrated_by { get; set; }
        public string CIIE_clientororgan_adresse { get; set; }
        public string CIIE_payment_trms { get; set; }
        public string CIIE_net_ht { get; set; }
        public string CIIE_tva_euro { get; set; }
        public string CIIE_net_non_taxable { get; set; }
        public string CIIE_net_douane { get; set; }
        public Nullable<int> CIIE_total_payment_amt { get; set; }
        public string CIIE_comments { get; set; }
        public string CIIE_ActiveStatus { get; set; }
        public string CIIE_CreateBy { get; set; }
        public System.DateTime CIIE_CreateOn { get; set; }
        public string CIIE_UpdateBy { get; set; }
        public Nullable<System.DateTime> CIIE_UpdateOn { get; set; }
    }
}
