//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIA_DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIUserMaster
    {
        public int CIUserMst_ID { get; set; }
        public string CIUM_LoginName { get; set; }
        public string CIUM_Password { get; set; }
        public string CIUM_UserName { get; set; }
        public string CIUM_UserRole { get; set; }
        public string CIUM_UserEmail { get; set; }
        public string CIUM_UserMobile { get; set; }
        public string CIUM_ActiveStatus { get; set; }
        public int CIUM_CreateBy { get; set; }
        public System.DateTime CIUM_CreateOn { get; set; }
        public Nullable<int> CIUM_UpdateBy { get; set; }
        public Nullable<System.DateTime> CIUM_UpdateOn { get; set; }
    }
}
